# Generated by Django 2.1.1 on 2018-10-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=20)),
                ('descripcionCategoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('precioProducto', models.FloatField(blank=True, default=0)),
                ('precioOfertaProducto', models.FloatField(blank=True, default=0)),
                ('tallaProducto', models.CharField(max_length=5)),
                ('colorProducto', models.CharField(max_length=20)),
                ('tipoProducto', models.CharField(max_length=20)),
                ('marcaProducto', models.CharField(max_length=50)),
                ('stockProducto', models.IntegerField()),
                ('imagenProducto', models.ImageField(upload_to='')),
                ('descripcionProducto', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumentoProveedor', models.CharField(max_length=20)),
                ('numeroDocumentoProveedor', models.CharField(max_length=11)),
                ('nombreProveedor', models.CharField(max_length=50)),
                ('direccionProveedor', models.CharField(max_length=50)),
                ('telefonoProveedor', models.CharField(max_length=9)),
                ('webProveedor', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Proveedor'),
        ),
    ]
