# Generated by Django 2.1.1 on 2018-10-29 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 21, 29, 37, 938618)),
        ),
    ]
