# Generated by Django 2.1.1 on 2018-12-16 01:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20181028_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoComprobante', models.CharField(max_length=7)),
                ('nroComprobante', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('cantidadinicial', models.FloatField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Lote')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 20, 30, 17, 391280)),
        ),
        migrations.AddField(
            model_name='producto_lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Producto'),
        ),
    ]
