# Generated by Django 2.1.1 on 2018-12-24 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20181215_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 16, 59, 9, 979578)),
        ),
    ]
