# Generated by Django 2.1.1 on 2018-12-24 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20181224_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_lote',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto_lote',
            name='cantidadinicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 17, 1, 26, 684912)),
        ),
    ]
