# Generated by Django 2.1.1 on 2018-12-25 03:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0006_auto_20181224_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='carroCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 22, 32, 7, 325260)),
        ),
    ]
