# Generated by Django 2.1.1 on 2018-12-25 12:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0008_auto_20181225_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEnTarjeta', models.CharField(max_length=30)),
                ('numeroTarjeta', models.CharField(max_length=16)),
                ('ccv', models.CharField(max_length=3)),
                ('fechaExpiracion', models.CharField(max_length=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 7, 3, 59, 693086)),
        ),
    ]
